// Platform-agnostic core: typed IPC wrappers over the Rust managers.
export type { VelixPlugin } from '@velix/sdk'
export type {
  NavigateRequest,
  Profile,
  Settings,
  Theme,
  UnreadEntry,
  UpdateInfo,
  UpdateStatus,
  WindowStatus,
} from './types'
export {
  listProfiles,
  createProfile,
  renameProfile,
  setProfileMuted,
  deleteProfile,
  openWebview,
  focusWebview,
  hideWebviews,
  closeWebview,
  setSidebarCollapsed,
  webviewBack,
  webviewForward,
  webviewReload,
  webviewSetZoom,
  lastProfile,
  appVersion,
  checkUpdate,
  installUpdate,
  getSettings,
  setTheme,
  setQuiet,
  setCloseToTray,
  setAutostart,
  showMainWindow,
  openSettings,
  openAccount,
  hideTrayPopup,
  listUnread,
  quitApp,
  windowIsMaximized,
  windowMinimize,
  windowToggleMaximize,
  windowClose,
  windowStartDrag,
  onUnread,
  onSettings,
  onWindowStatus,
  onNavigate,
  onUpdate,
} from './ipc'
